config/routes.rb
Rails.application.routes.draw do
  get 'friendships/create'
  get 'friendships/destroy'
  resources :notifications
  root 'posts#index'

  resources :posts do 
    resources :comments
    resources :likes
  end


  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'users/registrations'}
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  validates :post_id, :uniqueness => { :scope => :user_id }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :notification_text, :uniqueness => { :scope => :user_id } 
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.name = provider_data.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end

  has_many :posts
  has_many :comments
  has_many :notifications
  has_many :friendships
  has_many :friends, through: :friendships
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :notifications

  def notifications
    @notifications = current_user.notifications unless current_user.nil?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = Friendship.create(friendship_params)
    @inverse_friendship = Friendship.create(user_id: params[:friend_id], friend_id: params[:user_id])
    @user = current_user
    flash[:notice] = "Friendship created!"
    @notification = Notification.find_by_id(params[:notification])
    @notification.destroy
    redirect_to @user
  end

  def destroy
  end

  private
  def friendship_params
    params.permit(:user_id, :friend_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    @like = Like.create(user_id: current_user.id, post_id: @post.id)
    redirect_to @post
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    @user = current_user
    if @notification.save
      flash[:notice] = "Friend invited!"
    else
      flash[:notice] = "Friend already invited!"
    end
    redirect_to @user
  end

  def index
    @notifications = Notification.all
  end

  def destroy
    @notification = Notification.find_by_id(params[:id])
    @notification.destroy
    redirect_to root_path
  end

  private
  def notification_params
    params.permit(:notification_text, :user_id, :friend_id)
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  skip_before_action :authenticate_user!

  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
      flash[:notice] = 'You are successfully loged in with facebook!'
    else
      flash[:alert] = 'There was a problem signing you in through Facebook, Please register or try signing in later'
      redirect_to root_path
    end
  end

  def failure
    flash[:alert] = "there was an error, please sign up"
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to @post
    else
      flash[:alert] = "There is a mistake in your post!"
      render :new
    end
  end

  def edit

  end

  def update
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="new_post_button">
  <%= link_to "Create new post", new_post_path %>
</div>
<h1>Posts feed</h1>
<ul>
  <% @posts.each do |post| %>
    <% if post.user == current_user || current_user.friends.include?(post.user) %>
      <li>
        <%= link_to post.title, post %>
      </li>
    <% else %>
      <% next %>
    <% end %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="post_frame">
  <div class="post">
    <h3><%= @post.title %>, Author:<%= @post.user.name %></h3>
    <p><%= @post.body %><br></p>
  </div>
  <div class="comments">
    <div class="comment_text">
      <% @post.comments.each do |comment| %>
        Commenter name: <%= comment.user.name %><br>
        <%= comment.body %><br>
      <% end %>
    </div>
    <div class="new_comment">
      <%= simple_form_for [@post, @post.comments.build] do |f| %>
        <%= f.label :body, 'Enter your comment' %>
        <%= f.input :body, class:"input_comment", style: 'display: block;', label: false %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
  <br>
  Number of likes: <%= @post.likes.count %><br>
  <%= link_to "LIKE", post_likes_path(post_id: @post.id), method: "post" %>
</div>