config/routes.rb
Rails.application.routes.draw do
  get 'friendships/create'
  get 'friendships/destroy'
  resources :notifications
  root 'posts#index'

  resources :posts do 
    resources :comments
    resources :likes
  end


  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'users/registrations'}
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  validates :post_id, :uniqueness => { :scope => :user_id }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :notification_text, :uniqueness => { :scope => :user_id } 
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.name = provider_data.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end

  has_many :posts
  has_many :comments
  has_many :notifications
  has_many :friendships
  has_many :friends, through: :friendships
  has_one_attached :avatar
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    @like = Like.create(user_id: current_user.id, post_id: @post.id)
    redirect_to @post
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  skip_before_action :authenticate_user!

  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
      flash[:notice] = 'You are successfully loged in with facebook!'
    else
      flash[:alert] = 'There was a problem signing you in through Facebook, Please register or try signing in later'
      redirect_to root_path
    end
  end

  def failure
    flash[:alert] = "there was an error, please sign up"
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to @post
    else
      flash[:alert] = "There is a mistake in your post!"
      render :new
    end
  end

  def edit

  end

  def update
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash_messages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="navbar">
      <div class="profile_root">
        <%  unless current_user.nil? %>
          <%= link_to "#{current_user.name} profile", user_path(current_user.id), class:"profile" %>
        <% end %>
        <%= link_to "Main page", root_path, class:"root" %>
      </div>
      <div class="devise">
        <%= link_to "Sign up", new_user_registration_path, class:"devise_link" %>
        <%= link_to "Sign in", new_user_session_path, class:"devise_link" %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"devise_link" %>
      </div>
    </div>
    <div class="middle">
      <div class="yield">
        <%= yield %>
      </div>
      <div class="notifications">
        <% unless current_user.nil?%>
          <% @notifications.each do |notif| %>
            <%= notif.notification_text %>
            <%= button_to "Accept", friendships_create_path, params: { user_id: current_user.id, friend_id: notif.friend_id, notification: notif }, method: "get" %>
            <%= button_to "Reject", notification_path(notif), method: :delete %>
          <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>